include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false # Lines are 120 lines
    public_member_api_docs: false
    sort_constructors_first: false
